parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - 'plugin:@typescript-eslint/recommended'
  - next/core-web-vitals
  - prettier
plugins:
  - '@typescript-eslint'
  - prettier
root: true
rules:
  '@typescript-eslint/no-non-null-assertion': 0
  prettier/prettier: 2
  sort-keys:
    - error
    - asc
    - caseSensitive: true
      natural: false
